### ISSUE TITLE
Include Matomo tracking snippet in the module?

### ISSUE THREAD

**Issue by PierreMesure** [digidemlab/decidim-module-analytics#2]
At Digidem Lab, we've already included the tracking snippet in [the code of our app](https://github.com/digidemlab/decidim-sweden/blob/master/app/views/layouts/decidim/_matomo.html.erb).

However, it could be moved here so the module could take care of both tracking and visualising.

**Comment by microstudi** [comment]
Teorically just by creating the file `views/layouts/decidim/_head_extra.html.rb` with the snipped content (if configured) should be enough. However many installations have this file customized, so it would be nice to have some documentation about it

**Comment by PierreMesure** [comment]
Yes, I was thinking of doing something more respecful with a [_matomo.html.erb](https://github.com/digidemlab/decidim-sweden/blob/master/app/views/layouts/decidim/_matomo.html.erb) containing the snippet and installation instructions to add the line `<%= render partial: "layouts/decidim/matomo" %>` in your [_head_extra.html.rb](https://github.com/digidemlab/decidim-sweden/blob/master/app/views/layouts/decidim/_head_extra.html.erb).

I see that many instances (like [yours](https://github.com/Platoniq/decidim-bcnencomu/blob/master/app/views/layouts/decidim/_head_extra.html.erb)) still set the `server_address` and `site_id` manually so they would need to move to env variables or overwrite.

**Comment by microstudi** [comment]
That's a good approach, it also gives users the liberty to use custom approaches.
In here we allow to configure different Matomos per tenant:

https://github.com/Platoniq/decidim-openheritage/blob/master/app/views/layouts/decidim/_head_extra.html.erb
https://github.com/Platoniq/decidim-openheritage/blob/master/app/helpers/application_helper.rb
https://github.com/Platoniq/decidim-openheritage/blob/master/config/secrets.yml

**Comment by PierreMesure** [comment]
Fixed. Don't hesitate to review and give feedback but I think it's the best and simplest one for now, tracking is opt-in (since you need to add a line in `_head_extra.html.rb`. and it relies on the same secrets as in the backend.

I won't implement a multi-instance for now but I'm open to the idea.
